# Generated by Django 5.2.1 on 2025-06-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='data_primeira_consulta',
        ),
    ]
