# Generated by Django 5.2.1 on 2025-06-04 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0002_remove_paciente_data_primeira_consulta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lembrete', models.DateField()),
                ('texto', models.TextField()),
                ('concluido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='paciente.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_material', models.CharField(max_length=255)),
                ('enviado_em', models.DateTimeField(auto_now_add=True)),
                ('anotacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_enviados', to='paciente.anotacaocontato')),
                ('lembrete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_lembrete', to='paciente.lembrete')),
            ],
        ),
        migrations.CreateModel(
            name='RegraLembrete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dias_apos', models.IntegerField(help_text='Dias após o evento para criar o lembrete')),
                ('descricao', models.TextField()),
                ('primeira_consulta', models.BooleanField(default=False)),
                ('nutricionista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lembrete',
            name='regra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lembretes_criados', to='paciente.regralembrete'),
        ),
    ]
