# Generated by Django 5.2.1 on 2025-06-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0003_lembrete_materialenviado_regralembrete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='lembretes_ativos',
            field=models.BooleanField(default=True),
        ),
    ]
