# Generated by Django 4.2.22 on 2025-06-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0004_paciente_lembretes_ativos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regralembrete',
            name='primeira_consulta',
        ),
        migrations.AddField(
            model_name='regralembrete',
            name='ordem',
            field=models.IntegerField(default=1, help_text='Ordem de prioridade para a regra'),
            preserve_default=False,
        ),
    ]
