# Generated by Django 5.2.1 on 2025-06-06 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0005_remove_regralembrete_primeira_consulta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
