# Generated by Django 5.2.1 on 2025-06-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0006_paciente_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatonutricionista',
            name='tipo',
            field=models.CharField(blank=True, help_text='Ex: Whatsapp, Email, Telefone', max_length=255, null=True),
        ),
    ]
