# Generated by Django 5.2.1 on 2025-06-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0007_alter_contatonutricionista_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(default='Consulta', help_text='Ex: Consulta, Retorno', max_length=100),
        ),
    ]
