# Generated by Django 5.2.1 on 2025-06-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0008_consulta_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='tipo_consulta',
            field=models.CharField(default='consulta', help_text='Ex: Consulta, Retorno', max_length=100),
        ),
    ]
