# Generated by Django 5.2.1 on 2025-06-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0012_paciente_grupo_lembrete'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='contato_em',
            field=models.DateField(blank=True, null=True),
        ),
    ]
