# Generated by Django 5.2.4 on 2025-07-06 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0013_lembrete_contato_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regralembrete',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regras', to='paciente.grupolembrete'),
        ),
    ]
