# Generated by Django 5.2.4 on 2025-08-13 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0014_alter_regralembrete_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
