# Generated by Django 5.2.4 on 2025-09-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0015_alter_material_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='regralembrete',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
