# Generated by Django 5.2.4 on 2025-11-02 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0016_consulta_created_at_paciente_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regralembrete',
            name='materiais',
            field=models.ManyToManyField(blank=True, related_name='regras', to='paciente.material'),
        ),
    ]
