# Generated by Django 5.2.4 on 2025-11-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0017_regralembrete_materiais'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='whatsapp_disparado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lembrete',
            name='whatsapp_status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro'), ('sem_telefone', 'Sem telefone')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='lembrete',
            name='whatsapp_tentativas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lembrete',
            name='whatsapp_ultimo_erro',
            field=models.TextField(blank=True),
        ),
    ]
