# Generated by Django 5.2.4 on 2025-11-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0018_lembrete_whatsapp_disparado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='whatsapp_message_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID da mensagem retornado pela API do WhatsApp (messages[0].id).', max_length=255),
        ),
        migrations.AddField(
            model_name='lembrete',
            name='whatsapp_respondido_em',
            field=models.DateTimeField(blank=True, help_text='Data/hora em que o paciente respondeu ou interagiu pela primeira vez.', null=True),
        ),
        migrations.AddField(
            model_name='lembrete',
            name='whatsapp_resposta_id',
            field=models.CharField(blank=True, help_text='ID da resposta/interação (ex: button_reply.id).', max_length=100),
        ),
        migrations.AddField(
            model_name='lembrete',
            name='whatsapp_resposta_texto',
            field=models.TextField(blank=True, help_text='Conteúdo da resposta (ex: título do botão ou mensagem de texto).'),
        ),
    ]
