# Generated by Django 5.2.4 on 2025-12-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0019_lembrete_whatsapp_message_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteracaoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='lembrete',
            name='tipo_mensagem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
