# Generated by Django 4.2.27 on 2025-12-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0020_interacaowhatsapp_lembrete_tipo_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembrete',
            name='enviado_para',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
