# Generated by Django 4.2.27 on 2025-12-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0021_lembrete_enviado_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='arquivo_foto',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
        migrations.AddField(
            model_name='material',
            name='arquivo_imagem',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
        migrations.AddField(
            model_name='material',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
        migrations.AddField(
            model_name='material',
            name='arquivo_video',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
    ]
