# Generated by Django 4.2.27 on 2025-12-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0022_material_arquivo_foto_material_arquivo_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='tipo_arquivo',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('video', 'Video'), ('imagem', 'Imagem'), ('foto', 'Foto')], max_length=20, null=True),
        ),
    ]
