# Generated by Django 4.2.27 on 2025-12-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0027_material_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='tipo_arquivo',
            field=models.CharField(blank=True, choices=[('pdf', 'PDF'), ('video', 'Video'), ('imagem', 'Imagem'), ('foto', 'Foto'), ('youtube', 'Video do YouTube')], max_length=20, null=True),
        ),
    ]
