# Generated by Django 5.2.4 on 2026-01-11 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0029_material_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupolembrete',
            name='redirecionar_para',
            field=models.ForeignKey(blank=True, help_text='Ao finalizar o fluxo, redirecionar para este grupo (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_origem', to='paciente.grupolembrete'),
        ),
    ]
