# Generated by Django 5.2.4 on 2026-01-15 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0030_grupolembrete_redirecionar_para'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupolembrete',
            name='acao_final',
            field=models.CharField(choices=[('none', 'Nao fazer nada'), ('redirect', 'Redirecionar para outro fluxo'), ('loop', 'Envios recorrentes')], default='loop', help_text='O que fazer ao terminar o fluxo: none, redirect ou loop (recorrente).', max_length=20),
        ),
        migrations.AddField(
            model_name='grupolembrete',
            name='dias_recorrentes',
            field=models.PositiveIntegerField(blank=True, help_text='Intervalo fixo em dias quando acao_final=loop.', null=True),
        ),
    ]
