# Generated by Django 5.2.1 on 2025-06-14 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paciente', '0011_grupolembrete_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='grupo_lembrete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_paciente', to='paciente.grupolembrete'),
        ),
    ]
